//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemi.Resorces.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _Layout_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RandevuSistemi.Resorces.Shared._Layout.en", typeof(_Layout_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        internal static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        internal static string Cikis {
            get {
                return ResourceManager.GetString("Cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktorlar.
        /// </summary>
        internal static string Doktorlar {
            get {
                return ResourceManager.GetString("Doktorlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string Giris {
            get {
                return ResourceManager.GetString("Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poliklinikler.
        /// </summary>
        internal static string Poliklinikler {
            get {
                return ResourceManager.GetString("Poliklinikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randevu Al.
        /// </summary>
        internal static string RandevuAl {
            get {
                return ResourceManager.GetString("RandevuAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randevu Sistemi.
        /// </summary>
        internal static string RandevuSistemi {
            get {
                return ResourceManager.GetString("RandevuSistemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik.
        /// </summary>
        internal static string Uyelik {
            get {
                return ResourceManager.GetString("Uyelik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        internal static string UyeOl {
            get {
                return ResourceManager.GetString("UyeOl", resourceCulture);
            }
        }
    }
}
